# Generated by Django 5.2.11 on 2026-02-19 20:48

import django.db.models.deletion
import django.utils.timezone
import users.managers
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует'}, max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким логином уже существует'}, max_length=150, unique=True, validators=[users.validators.validate_nickname], verbose_name='логин')),
                ('first_name', models.CharField(max_length=150, validators=[users.validators.validate_name], verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, validators=[users.validators.validate_name], verbose_name='фамилия')),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='avatars/%Y/%m/', verbose_name='аватар')),
                ('is_staff', models.BooleanField(default=False, help_text='Доступ к админ-панели', verbose_name='статус персонала')),
                ('is_active', models.BooleanField(default=True, help_text='Деактивируйте вместо удаления', verbose_name='активен')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', users.managers.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата подписки')),
                ('subscriber', models.ForeignKey(help_text='Кто подписывается', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='подписчик')),
                ('target', models.ForeignKey(help_text='Цель подписки', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='на кого подписан')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['email'], name='users_usera_email_482885_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['username'], name='users_usera_usernam_849d9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='followrelationship',
            constraint=models.UniqueConstraint(fields=('subscriber', 'target'), name='unique_follow'),
        ),
        # migrations.AddConstraint(
            # model_name='followrelationship',
            # constraint=models.CheckConstraint(condition=models.Q(('subscriber', models.F('target')), _negated=True), name='no_self_follow'),
        # ),
    ]
