# Generated by Django 5.2.11 on 2026-02-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='followrelationship',
            constraint=models.CheckConstraint(
                check=~models.Q(subscriber=models.F('target')),
                name='no_self_follow'
            ),
        ),
    ]
